version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    container_name: 'rabbitmq'
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 10
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - './rabbitmq:/var/lib/rabbitmq/mnesia'
    networks:
        - rabbitmq_net
  background_worker:
    build: ./background_worker
    restart: on-failure
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq/
      - INPUT_QUEUE=input
      - OUTPUT_QUEUE=output
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
  http_api:
    build: ./http_api
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq/
      - INPUT_QUEUE=input
    depends_on:
      - rabbitmq
      - background_worker
    networks:
      - rabbitmq_net
  web_socket_api:
    build: ./web_socket_api
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq/
      - OUTPUT_QUEUE=output
    depends_on:
      - rabbitmq
      - background_worker
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge